// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: connector_stream_service.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/// Adapted from third_party/firebase/dataconnect/emulator/server/api/connector_stream_service.proto

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// StreamRequest defines the request of Data Connect's bi-directional streaming
/// API.
///
/// It supports 4 different request kinds:
/// - Subscribe: Subscribe to the result of a Data Connect query.
/// - Execute: Execute a Data Connect query or mutation.
/// - Resume: Resume a query or part of it.
/// - Cancel: Signal that the client is no longer interested in the result of
/// this operation.
public struct Google_Firebase_Dataconnect_V1_StreamRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The resource name of the connector to find the predefined query, in
  /// the format:
  /// ```
  /// projects/{project}/locations/{location}/services/{service}/connectors/{connector}
  /// ```
  /// Only needed for the first request of rpc Stream.
  public var name: String = String()

  /// The HTTP headers to use for the request.
  /// (-- See go/fdc-realtime-headers --)
  public var headers: Dictionary<String,String> = [:]

  /// The request id used to identify a request within the stream.
  /// It only needs to be unique within the stream, commonly a monotonically
  /// increasing sequence number per stream.
  /// (-- api-linter: core::0155::request-id-format=disabled
  ///     aip.dev/not-precedent: request_id is only unique within the stream. --)
  public var requestID: String = String()

  /// The kind of request.
  public var requestKind: Google_Firebase_Dataconnect_V1_StreamRequest.OneOf_RequestKind? = nil

  /// Subscribe to the result of a Data Connect query.
  /// Watch for any subsequent changes until it’s cancelled by either client or
  /// backend.
  ///
  /// Must provide a new stream request id.
  public var subscribe: Google_Firebase_Dataconnect_V1_ExecuteRequest {
    get {
      if case .subscribe(let v)? = requestKind {return v}
      return Google_Firebase_Dataconnect_V1_ExecuteRequest()
    }
    set {requestKind = .subscribe(newValue)}
  }

  /// Execute a Data Connect query or mutation.
  ///
  /// Must provide a new stream request id.
  public var execute: Google_Firebase_Dataconnect_V1_ExecuteRequest {
    get {
      if case .execute(let v)? = requestKind {return v}
      return Google_Firebase_Dataconnect_V1_ExecuteRequest()
    }
    set {requestKind = .execute(newValue)}
  }

  /// Resume a query or part of it.
  ///
  /// Prefer an existing stream request id.
  /// Though it can send a new request if the connection was interrupted.
  public var resume: Google_Firebase_Dataconnect_V1_ResumeRequest {
    get {
      if case .resume(let v)? = requestKind {return v}
      return Google_Firebase_Dataconnect_V1_ResumeRequest()
    }
    set {requestKind = .resume(newValue)}
  }

  /// Signal that the client is no longer interested in the result of this
  /// operation.
  public var cancel: SwiftProtobuf.Google_Protobuf_Empty {
    get {
      if case .cancel(let v)? = requestKind {return v}
      return SwiftProtobuf.Google_Protobuf_Empty()
    }
    set {requestKind = .cancel(newValue)}
  }

  /// A server-provided ETag for the data payload.
  /// To save bandwidth, include this ETag in subsequent requests to prevent
  /// the server from resending data that has not changed.
  public var dataEtag: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  /// The kind of request.
  public enum OneOf_RequestKind: Equatable, Sendable {
    /// Subscribe to the result of a Data Connect query.
    /// Watch for any subsequent changes until it’s cancelled by either client or
    /// backend.
    ///
    /// Must provide a new stream request id.
    case subscribe(Google_Firebase_Dataconnect_V1_ExecuteRequest)
    /// Execute a Data Connect query or mutation.
    ///
    /// Must provide a new stream request id.
    case execute(Google_Firebase_Dataconnect_V1_ExecuteRequest)
    /// Resume a query or part of it.
    ///
    /// Prefer an existing stream request id.
    /// Though it can send a new request if the connection was interrupted.
    case resume(Google_Firebase_Dataconnect_V1_ResumeRequest)
    /// Signal that the client is no longer interested in the result of this
    /// operation.
    case cancel(SwiftProtobuf.Google_Protobuf_Empty)

  }

  public init() {}
}

/// ExecuteRequest defines the request to execute a Data Connect query or
/// mutation.
public struct Google_Firebase_Dataconnect_V1_ExecuteRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The name of the GraphQL operation name.
  /// Required because all connector operations must be named.
  /// See https://graphql.org/learn/queries/#operation-name.
  /// (-- api-linter: core::0122::name-suffix=disabled
  ///     aip.dev/not-precedent: Must conform to GraphQL HTTP spec standard. --)
  public var operationName: String = String()

  /// Values for GraphQL variables provided in this request.
  public var variables: SwiftProtobuf.Google_Protobuf_Struct {
    get {return _variables ?? SwiftProtobuf.Google_Protobuf_Struct()}
    set {_variables = newValue}
  }
  /// Returns true if `variables` has been explicitly set.
  public var hasVariables: Bool {return self._variables != nil}
  /// Clears the value of `variables`. Subsequent reads from it will return its default value.
  public mutating func clearVariables() {self._variables = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _variables: SwiftProtobuf.Google_Protobuf_Struct? = nil
}

/// ResumeRequest defines the request to resume a query or part of it.
public struct Google_Firebase_Dataconnect_V1_ResumeRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// StreamResponse defines the response of Data Connect's bi-directional
/// streaming API.
public struct Google_Firebase_Dataconnect_V1_StreamResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Identify which request this response is for.
  /// (-- api-linter: core::0155::request-id-format=disabled
  ///     aip.dev/not-precedent: request_id is only unique within the stream. --)
  public var requestID: String = String()

  /// The result of executing the requested operation.
  public var data: SwiftProtobuf.Google_Protobuf_Struct {
    get {return _data ?? SwiftProtobuf.Google_Protobuf_Struct()}
    set {_data = newValue}
  }
  /// Returns true if `data` has been explicitly set.
  public var hasData: Bool {return self._data != nil}
  /// Clears the value of `data`. Subsequent reads from it will return its default value.
  public mutating func clearData() {self._data = nil}

  /// The backend may return a data_etag, computed based on the data JSON
  /// payload.
  ///
  /// To save bandwidth, the Data Connect SDK should include data_etag of cached
  /// data in subsequent requests, so the backend can avoid sending redundant
  /// data already in SDK cache.
  public var dataEtag: String = String()

  /// Errors of this response.
  public var errors: [Google_Firebase_Dataconnect_V1_GraphqlError] = []

  /// The backend can no longer serve this operation.
  /// For example, it may become invalid after schema change.
  public var cancelled: Bool = false

  /// Additional response information.
  public var extensions: Google_Firebase_Dataconnect_V1_GraphqlResponseExtensions {
    get {return _extensions ?? Google_Firebase_Dataconnect_V1_GraphqlResponseExtensions()}
    set {_extensions = newValue}
  }
  /// Returns true if `extensions` has been explicitly set.
  public var hasExtensions: Bool {return self._extensions != nil}
  /// Clears the value of `extensions`. Subsequent reads from it will return its default value.
  public mutating func clearExtensions() {self._extensions = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _data: SwiftProtobuf.Google_Protobuf_Struct? = nil
  fileprivate var _extensions: Google_Firebase_Dataconnect_V1_GraphqlResponseExtensions? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "google.firebase.dataconnect.v1"

extension Google_Firebase_Dataconnect_V1_StreamRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StreamRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "name"),
    10: .same(proto: "headers"),
    2: .standard(proto: "request_id"),
    3: .same(proto: "subscribe"),
    4: .same(proto: "execute"),
    5: .same(proto: "resume"),
    6: .same(proto: "cancel"),
    8: .standard(proto: "data_etag"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.requestID) }()
      case 3: try {
        var v: Google_Firebase_Dataconnect_V1_ExecuteRequest?
        var hadOneofValue = false
        if let current = self.requestKind {
          hadOneofValue = true
          if case .subscribe(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.requestKind = .subscribe(v)
        }
      }()
      case 4: try {
        var v: Google_Firebase_Dataconnect_V1_ExecuteRequest?
        var hadOneofValue = false
        if let current = self.requestKind {
          hadOneofValue = true
          if case .execute(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.requestKind = .execute(v)
        }
      }()
      case 5: try {
        var v: Google_Firebase_Dataconnect_V1_ResumeRequest?
        var hadOneofValue = false
        if let current = self.requestKind {
          hadOneofValue = true
          if case .resume(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.requestKind = .resume(v)
        }
      }()
      case 6: try {
        var v: SwiftProtobuf.Google_Protobuf_Empty?
        var hadOneofValue = false
        if let current = self.requestKind {
          hadOneofValue = true
          if case .cancel(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.requestKind = .cancel(v)
        }
      }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.dataEtag) }()
      case 10: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.headers) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.requestID.isEmpty {
      try visitor.visitSingularStringField(value: self.requestID, fieldNumber: 2)
    }
    switch self.requestKind {
    case .subscribe?: try {
      guard case .subscribe(let v)? = self.requestKind else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .execute?: try {
      guard case .execute(let v)? = self.requestKind else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .resume?: try {
      guard case .resume(let v)? = self.requestKind else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case .cancel?: try {
      guard case .cancel(let v)? = self.requestKind else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    }()
    case nil: break
    }
    if !self.dataEtag.isEmpty {
      try visitor.visitSingularStringField(value: self.dataEtag, fieldNumber: 8)
    }
    if !self.headers.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.headers, fieldNumber: 10)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Google_Firebase_Dataconnect_V1_StreamRequest, rhs: Google_Firebase_Dataconnect_V1_StreamRequest) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.headers != rhs.headers {return false}
    if lhs.requestID != rhs.requestID {return false}
    if lhs.requestKind != rhs.requestKind {return false}
    if lhs.dataEtag != rhs.dataEtag {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Google_Firebase_Dataconnect_V1_ExecuteRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ExecuteRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    2: .standard(proto: "operation_name"),
    3: .same(proto: "variables"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try { try decoder.decodeSingularStringField(value: &self.operationName) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._variables) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.operationName.isEmpty {
      try visitor.visitSingularStringField(value: self.operationName, fieldNumber: 2)
    }
    try { if let v = self._variables {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Google_Firebase_Dataconnect_V1_ExecuteRequest, rhs: Google_Firebase_Dataconnect_V1_ExecuteRequest) -> Bool {
    if lhs.operationName != rhs.operationName {return false}
    if lhs._variables != rhs._variables {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Google_Firebase_Dataconnect_V1_ResumeRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ResumeRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Google_Firebase_Dataconnect_V1_ResumeRequest, rhs: Google_Firebase_Dataconnect_V1_ResumeRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Google_Firebase_Dataconnect_V1_StreamResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StreamResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "request_id"),
    2: .same(proto: "data"),
    4: .standard(proto: "data_etag"),
    3: .same(proto: "errors"),
    5: .same(proto: "cancelled"),
    6: .same(proto: "extensions"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._data) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.errors) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.dataEtag) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.cancelled) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._extensions) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.requestID.isEmpty {
      try visitor.visitSingularStringField(value: self.requestID, fieldNumber: 1)
    }
    try { if let v = self._data {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if !self.errors.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.errors, fieldNumber: 3)
    }
    if !self.dataEtag.isEmpty {
      try visitor.visitSingularStringField(value: self.dataEtag, fieldNumber: 4)
    }
    if self.cancelled != false {
      try visitor.visitSingularBoolField(value: self.cancelled, fieldNumber: 5)
    }
    try { if let v = self._extensions {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Google_Firebase_Dataconnect_V1_StreamResponse, rhs: Google_Firebase_Dataconnect_V1_StreamResponse) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs._data != rhs._data {return false}
    if lhs.dataEtag != rhs.dataEtag {return false}
    if lhs.errors != rhs.errors {return false}
    if lhs.cancelled != rhs.cancelled {return false}
    if lhs._extensions != rhs._extensions {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
