//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: connector_stream_service.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// ConnectorStreamService provides bi-directional streaming APIs to use with
/// Firebase Data Connect connectors.
///
/// Usage: instantiate `Google_Firebase_Dataconnect_V1_ConnectorStreamServiceClient`, then call methods of this protocol to make API calls.
public protocol Google_Firebase_Dataconnect_V1_ConnectorStreamServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Google_Firebase_Dataconnect_V1_ConnectorStreamServiceClientInterceptorFactoryProtocol? { get }

  func connect(
    callOptions: CallOptions?,
    handler: @escaping (Google_Firebase_Dataconnect_V1_StreamResponse) -> Void
  ) -> BidirectionalStreamingCall<Google_Firebase_Dataconnect_V1_StreamRequest, Google_Firebase_Dataconnect_V1_StreamResponse>
}

extension Google_Firebase_Dataconnect_V1_ConnectorStreamServiceClientProtocol {
  public var serviceName: String {
    return "google.firebase.dataconnect.v1.ConnectorStreamService"
  }

  /// Connect establishes a bi-directional connection to the server.
  /// The client can send new requests, resume requests, and receive realtime
  /// updates.
  ///
  /// The connection may last for hours, the Data Connect SDK should refresh
  /// Firebase auth token to avoid revoked query subscriptions.
  ///
  /// (-- api-linter: core::0136::verb-noun=disabled
  ///     aip.dev/not-precedent: Connect is a general purpose streaming API. --)
  ///
  /// Callers should use the `send` method on the returned object to send messages
  /// to the server. The caller should send an `.end` after the final message has been sent.
  ///
  /// - Parameters:
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ClientStreamingCall` with futures for the metadata and status.
  public func connect(
    callOptions: CallOptions? = nil,
    handler: @escaping (Google_Firebase_Dataconnect_V1_StreamResponse) -> Void
  ) -> BidirectionalStreamingCall<Google_Firebase_Dataconnect_V1_StreamRequest, Google_Firebase_Dataconnect_V1_StreamResponse> {
    return self.makeBidirectionalStreamingCall(
      path: Google_Firebase_Dataconnect_V1_ConnectorStreamServiceClientMetadata.Methods.connect.path,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeConnectInterceptors() ?? [],
      handler: handler
    )
  }
}

@available(*, deprecated)
extension Google_Firebase_Dataconnect_V1_ConnectorStreamServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Google_Firebase_Dataconnect_V1_ConnectorStreamServiceNIOClient")
public final class Google_Firebase_Dataconnect_V1_ConnectorStreamServiceClient: Google_Firebase_Dataconnect_V1_ConnectorStreamServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Google_Firebase_Dataconnect_V1_ConnectorStreamServiceClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Google_Firebase_Dataconnect_V1_ConnectorStreamServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the google.firebase.dataconnect.v1.ConnectorStreamService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Google_Firebase_Dataconnect_V1_ConnectorStreamServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Google_Firebase_Dataconnect_V1_ConnectorStreamServiceNIOClient: Google_Firebase_Dataconnect_V1_ConnectorStreamServiceClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Google_Firebase_Dataconnect_V1_ConnectorStreamServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the google.firebase.dataconnect.v1.ConnectorStreamService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Google_Firebase_Dataconnect_V1_ConnectorStreamServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// ConnectorStreamService provides bi-directional streaming APIs to use with
/// Firebase Data Connect connectors.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Google_Firebase_Dataconnect_V1_ConnectorStreamServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Google_Firebase_Dataconnect_V1_ConnectorStreamServiceClientInterceptorFactoryProtocol? { get }

  func makeConnectCall(
    callOptions: CallOptions?
  ) -> GRPCAsyncBidirectionalStreamingCall<Google_Firebase_Dataconnect_V1_StreamRequest, Google_Firebase_Dataconnect_V1_StreamResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Google_Firebase_Dataconnect_V1_ConnectorStreamServiceAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Google_Firebase_Dataconnect_V1_ConnectorStreamServiceClientMetadata.serviceDescriptor
  }

  public var interceptors: Google_Firebase_Dataconnect_V1_ConnectorStreamServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeConnectCall(
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncBidirectionalStreamingCall<Google_Firebase_Dataconnect_V1_StreamRequest, Google_Firebase_Dataconnect_V1_StreamResponse> {
    return self.makeAsyncBidirectionalStreamingCall(
      path: Google_Firebase_Dataconnect_V1_ConnectorStreamServiceClientMetadata.Methods.connect.path,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeConnectInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Google_Firebase_Dataconnect_V1_ConnectorStreamServiceAsyncClientProtocol {
  public func connect<RequestStream>(
    _ requests: RequestStream,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<Google_Firebase_Dataconnect_V1_StreamResponse> where RequestStream: Sequence, RequestStream.Element == Google_Firebase_Dataconnect_V1_StreamRequest {
    return self.performAsyncBidirectionalStreamingCall(
      path: Google_Firebase_Dataconnect_V1_ConnectorStreamServiceClientMetadata.Methods.connect.path,
      requests: requests,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeConnectInterceptors() ?? []
    )
  }

  public func connect<RequestStream>(
    _ requests: RequestStream,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<Google_Firebase_Dataconnect_V1_StreamResponse> where RequestStream: AsyncSequence & Sendable, RequestStream.Element == Google_Firebase_Dataconnect_V1_StreamRequest {
    return self.performAsyncBidirectionalStreamingCall(
      path: Google_Firebase_Dataconnect_V1_ConnectorStreamServiceClientMetadata.Methods.connect.path,
      requests: requests,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeConnectInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Google_Firebase_Dataconnect_V1_ConnectorStreamServiceAsyncClient: Google_Firebase_Dataconnect_V1_ConnectorStreamServiceAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Google_Firebase_Dataconnect_V1_ConnectorStreamServiceClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Google_Firebase_Dataconnect_V1_ConnectorStreamServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

public protocol Google_Firebase_Dataconnect_V1_ConnectorStreamServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'connect'.
  func makeConnectInterceptors() -> [ClientInterceptor<Google_Firebase_Dataconnect_V1_StreamRequest, Google_Firebase_Dataconnect_V1_StreamResponse>]
}

public enum Google_Firebase_Dataconnect_V1_ConnectorStreamServiceClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "ConnectorStreamService",
    fullName: "google.firebase.dataconnect.v1.ConnectorStreamService",
    methods: [
      Google_Firebase_Dataconnect_V1_ConnectorStreamServiceClientMetadata.Methods.connect,
    ]
  )

  public enum Methods {
    public static let connect = GRPCMethodDescriptor(
      name: "Connect",
      path: "/google.firebase.dataconnect.v1.ConnectorStreamService/Connect",
      type: GRPCCallType.bidirectionalStreaming
    )
  }
}

/// ConnectorStreamService provides bi-directional streaming APIs to use with
/// Firebase Data Connect connectors.
///
/// To build a server, implement a class that conforms to this protocol.
public protocol Google_Firebase_Dataconnect_V1_ConnectorStreamServiceProvider: CallHandlerProvider {
  var interceptors: Google_Firebase_Dataconnect_V1_ConnectorStreamServiceServerInterceptorFactoryProtocol? { get }

  /// Connect establishes a bi-directional connection to the server.
  /// The client can send new requests, resume requests, and receive realtime
  /// updates.
  ///
  /// The connection may last for hours, the Data Connect SDK should refresh
  /// Firebase auth token to avoid revoked query subscriptions.
  ///
  /// (-- api-linter: core::0136::verb-noun=disabled
  ///     aip.dev/not-precedent: Connect is a general purpose streaming API. --)
  func connect(context: StreamingResponseCallContext<Google_Firebase_Dataconnect_V1_StreamResponse>) -> EventLoopFuture<(StreamEvent<Google_Firebase_Dataconnect_V1_StreamRequest>) -> Void>
}

extension Google_Firebase_Dataconnect_V1_ConnectorStreamServiceProvider {
  public var serviceName: Substring {
    return Google_Firebase_Dataconnect_V1_ConnectorStreamServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Connect":
      return BidirectionalStreamingServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Firebase_Dataconnect_V1_StreamRequest>(),
        responseSerializer: ProtobufSerializer<Google_Firebase_Dataconnect_V1_StreamResponse>(),
        interceptors: self.interceptors?.makeConnectInterceptors() ?? [],
        observerFactory: self.connect(context:)
      )

    default:
      return nil
    }
  }
}

/// ConnectorStreamService provides bi-directional streaming APIs to use with
/// Firebase Data Connect connectors.
///
/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Google_Firebase_Dataconnect_V1_ConnectorStreamServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Google_Firebase_Dataconnect_V1_ConnectorStreamServiceServerInterceptorFactoryProtocol? { get }

  /// Connect establishes a bi-directional connection to the server.
  /// The client can send new requests, resume requests, and receive realtime
  /// updates.
  ///
  /// The connection may last for hours, the Data Connect SDK should refresh
  /// Firebase auth token to avoid revoked query subscriptions.
  ///
  /// (-- api-linter: core::0136::verb-noun=disabled
  ///     aip.dev/not-precedent: Connect is a general purpose streaming API. --)
  func connect(
    requestStream: GRPCAsyncRequestStream<Google_Firebase_Dataconnect_V1_StreamRequest>,
    responseStream: GRPCAsyncResponseStreamWriter<Google_Firebase_Dataconnect_V1_StreamResponse>,
    context: GRPCAsyncServerCallContext
  ) async throws
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Google_Firebase_Dataconnect_V1_ConnectorStreamServiceAsyncProvider {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Google_Firebase_Dataconnect_V1_ConnectorStreamServiceServerMetadata.serviceDescriptor
  }

  public var serviceName: Substring {
    return Google_Firebase_Dataconnect_V1_ConnectorStreamServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  public var interceptors: Google_Firebase_Dataconnect_V1_ConnectorStreamServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Connect":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Firebase_Dataconnect_V1_StreamRequest>(),
        responseSerializer: ProtobufSerializer<Google_Firebase_Dataconnect_V1_StreamResponse>(),
        interceptors: self.interceptors?.makeConnectInterceptors() ?? [],
        wrapping: { try await self.connect(requestStream: $0, responseStream: $1, context: $2) }
      )

    default:
      return nil
    }
  }
}

public protocol Google_Firebase_Dataconnect_V1_ConnectorStreamServiceServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'connect'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeConnectInterceptors() -> [ServerInterceptor<Google_Firebase_Dataconnect_V1_StreamRequest, Google_Firebase_Dataconnect_V1_StreamResponse>]
}

public enum Google_Firebase_Dataconnect_V1_ConnectorStreamServiceServerMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "ConnectorStreamService",
    fullName: "google.firebase.dataconnect.v1.ConnectorStreamService",
    methods: [
      Google_Firebase_Dataconnect_V1_ConnectorStreamServiceServerMetadata.Methods.connect,
    ]
  )

  public enum Methods {
    public static let connect = GRPCMethodDescriptor(
      name: "Connect",
      path: "/google.firebase.dataconnect.v1.ConnectorStreamService/Connect",
      type: GRPCCallType.bidirectionalStreaming
    )
  }
}
