// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: graphql_response_extensions.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Adapted from third_party/firebase/dataconnect/emulator/server/api/graphql_response_extensions.proto

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// GraphqlResponseExtensions contains additional information of
/// `GraphqlResponse` or `ExecuteQueryResponse`.
public struct Google_Firebase_Dataconnect_V1_GraphqlResponseExtensions: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Data Connect specific GraphQL extension, a list of paths and properties.
  /// (-- Future fields should go inside to avoid name conflicts with other GQL
  /// extensions in the wild unless we're implementing a common 3P pattern in
  /// extensions such as versioning and telemetry. --)
  public var dataConnect: [Google_Firebase_Dataconnect_V1_GraphqlResponseExtensions.DataConnectProperties] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  /// Data Connect specific properties for a path under response.data.
  /// (-- Design doc: http://go/fdc-caching-wire-protocol --)
  public struct DataConnectProperties: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// The path under response.data where the rest of the fields apply.
    /// Each element may be a string (field name) or number (array index).
    /// The root of response.data is denoted by the empty list `[]`.
    /// (-- To simplify client logic, the server should never set this to null.
    /// i.e. Use `[]` if the properties below apply to everything in data. --)
    public var path: SwiftProtobuf.Google_Protobuf_ListValue {
      get {return _path ?? SwiftProtobuf.Google_Protobuf_ListValue()}
      set {_path = newValue}
    }
    /// Returns true if `path` has been explicitly set.
    public var hasPath: Bool {return self._path != nil}
    /// Clears the value of `path`. Subsequent reads from it will return its default value.
    public mutating func clearPath() {self._path = nil}

    /// A single Entity ID. Set if the path points to a single entity.
    public var entityID: String = String()

    /// A list of Entity IDs. Set if the path points to an array of entities. An
    /// ID is present for each element of the array at the corresponding index.
    public var entityIds: [String] = []

    /// The server-suggested duration before data under path is considered stale.
    /// (-- Right now, this field is never set. For future plans, see
    /// http://go/fdc-sdk-caching-config#heading=h.rmvncy2rao3g --)
    public var maxAge: SwiftProtobuf.Google_Protobuf_Duration {
      get {return _maxAge ?? SwiftProtobuf.Google_Protobuf_Duration()}
      set {_maxAge = newValue}
    }
    /// Returns true if `maxAge` has been explicitly set.
    public var hasMaxAge: Bool {return self._maxAge != nil}
    /// Clears the value of `maxAge`. Subsequent reads from it will return its default value.
    public mutating func clearMaxAge() {self._maxAge = nil}

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _path: SwiftProtobuf.Google_Protobuf_ListValue? = nil
    fileprivate var _maxAge: SwiftProtobuf.Google_Protobuf_Duration? = nil
  }

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "google.firebase.dataconnect.v1"

extension Google_Firebase_Dataconnect_V1_GraphqlResponseExtensions: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GraphqlResponseExtensions"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "data_connect"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.dataConnect) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.dataConnect.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.dataConnect, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Google_Firebase_Dataconnect_V1_GraphqlResponseExtensions, rhs: Google_Firebase_Dataconnect_V1_GraphqlResponseExtensions) -> Bool {
    if lhs.dataConnect != rhs.dataConnect {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Google_Firebase_Dataconnect_V1_GraphqlResponseExtensions.DataConnectProperties: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Google_Firebase_Dataconnect_V1_GraphqlResponseExtensions.protoMessageName + ".DataConnectProperties"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "path"),
    2: .standard(proto: "entity_id"),
    3: .standard(proto: "entity_ids"),
    4: .standard(proto: "max_age"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._path) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.entityID) }()
      case 3: try { try decoder.decodeRepeatedStringField(value: &self.entityIds) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._maxAge) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._path {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.entityID.isEmpty {
      try visitor.visitSingularStringField(value: self.entityID, fieldNumber: 2)
    }
    if !self.entityIds.isEmpty {
      try visitor.visitRepeatedStringField(value: self.entityIds, fieldNumber: 3)
    }
    try { if let v = self._maxAge {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Google_Firebase_Dataconnect_V1_GraphqlResponseExtensions.DataConnectProperties, rhs: Google_Firebase_Dataconnect_V1_GraphqlResponseExtensions.DataConnectProperties) -> Bool {
    if lhs._path != rhs._path {return false}
    if lhs.entityID != rhs.entityID {return false}
    if lhs.entityIds != rhs.entityIds {return false}
    if lhs._maxAge != rhs._maxAge {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
