# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.




#  **IMPORTANT**
#   Before deploying, be sure to change the auth level to something higher than PUBLIC

query GetItem($id: UUID!) @auth(level: PUBLIC) {
    item(id: $id) {
        id
        name
        desc
        #price
    }
}

query ListItems @auth(level: PUBLIC) {
    items {
        id
        name
        #price #Uncomment this to include price in the query
    }
}

