name: spm

on:
  pull_request:
  schedule:
    # Run every day at 11pm (PST) - cron uses UTC times
    - cron:  '0 7 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  changed_today:
    runs-on: ubuntu-latest
    name: Check if the repo was updated today
    outputs:
      WAS_CHANGED: ${{ steps.check_changed.outputs.WAS_CHANGED }}
    steps:
      - uses: actions/checkout@v4
      - id: check_changed
        name: Check
        if: ${{ github.event_name == 'schedule' }}
        run: echo '::set-output name=WAS_CHANGED::'$(test -n "$(git log --format=%H --since='24 hours ago')" && echo 'true' || echo 'false')

  spm:
    needs: changed_today
    if: ${{ github.event_name == 'pull_request' || needs.changed_today.outputs.WAS_CHANGED == 'true' }}

    strategy:
      matrix:
        os: [macos-14]
        # Target and Xcode matrix commented to workaround GHA download overload crashes
        # target: [iOS, tvOS, macOS, catalyst, visionOS]
        # xcode: [Xcode_15.2, Xcode_16_Release_Candidate]
    runs-on: ${{ matrix.os }}
    env:
      FIREBASE_MAIN: 1
    steps:
    - uses: actions/checkout@v4
    - name: Setup Scripts Directory
      run: ./setup-scripts.sh
    - name: Xcode 15
      run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer
    - name: Initialize xcodebuild
      run: xcodebuild -list
    - name: iOS Unit Tests
      run: scripts/third_party/travis/retry.sh scripts/build.sh FirebaseDataConnect iOS spm
    - name: tvOS Unit Tests
      run: scripts/third_party/travis/retry.sh scripts/build.sh FirebaseDataConnect tvOS spm
    - name: macOS Unit Tests
      run: scripts/third_party/travis/retry.sh scripts/build.sh FirebaseDataConnect macOS spm
    - name: visionOS Unit Tests
      run: scripts/third_party/travis/retry.sh scripts/build.sh FirebaseDataConnect visionOS spm
